// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa19BTw0BxyXvUKpPbh5ixt0bGpGPCXNQ',
    appId: '1:495644186003:web:a57e0d727fe2c949d28466',
    messagingSenderId: '495644186003',
    projectId: 'career-connect-app',
    authDomain: 'career-connect-app.firebaseapp.com',
    storageBucket: 'career-connect-app.firebasestorage.app',
    measurementId: 'G-8HEELD7PTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApxdebRbekE5oOzjaKKPVq-Q75wHeWAvE',
    appId: '1:495644186003:android:107f586357bbd379d28466',
    messagingSenderId: '495644186003',
    projectId: 'career-connect-app',
    storageBucket: 'career-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyoPQSDY5s3FRWv52ok7smEA2djmcBxU',
    appId: '1:495644186003:ios:a11ace71a694b65ed28466',
    messagingSenderId: '495644186003',
    projectId: 'career-connect-app',
    storageBucket: 'career-connect-app.firebasestorage.app',
    iosBundleId: 'com.careerconnect.careerConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyoPQSDY5s3FRWv52ok7smEA2djmcBxU',
    appId: '1:495644186003:ios:a11ace71a694b65ed28466',
    messagingSenderId: '495644186003',
    projectId: 'career-connect-app',
    storageBucket: 'career-connect-app.firebasestorage.app',
    iosBundleId: 'com.careerconnect.careerConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa19BTw0BxyXvUKpPbh5ixt0bGpGPCXNQ',
    appId: '1:495644186003:web:46febd708d0f2df6d28466',
    messagingSenderId: '495644186003',
    projectId: 'career-connect-app',
    authDomain: 'career-connect-app.firebaseapp.com',
    storageBucket: 'career-connect-app.firebasestorage.app',
    measurementId: 'G-N4TJY0P5VQ',
  );
}
